const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#FF6B00",
    background: "#FAFAFA",
    foreground: "#0a0a0a",
    card: "#FFFFFF",
    cardForeground: "#0a0a0a",
    primary: "#FF6B00",
    primaryForeground: "#FFFFFF",
    secondary: "#F5F5F5",
    secondaryForeground: "#1a1a1a",
    muted: "#F0F0F0",
    mutedForeground: "#737373",
    accent: "#FF9500",
    accentForeground: "#FFFFFF",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#E5E5E5",
    input: "#E5E5E5",
  },
  dark: {
    text: "#F2F2FF",
    tint: "#FF6B00",
    background: "#08080F",
    foreground: "#F2F2FF",
    card: "#10101E",
    cardForeground: "#F2F2FF",
    primary: "#FF6B00",
    primaryForeground: "#FFFFFF",
    secondary: "#18182A",
    secondaryForeground: "#F2F2FF",
    muted: "#18182A",
    mutedForeground: "#8888AA",
    accent: "#FF9500",
    accentForeground: "#FFFFFF",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1E1E35",
    input: "#1E1E35",
  },
  radius: 16,
};

export default colors;
